import type { Promo, FormSubmission } from './types'

export function isDevMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
  return url.includes('your-project') || url === ''
}

export const MOCK_PROMOS: Promo[] = [
  {
    id: 'mock-1',
    name: 'Home 0D 100Mbps',
    price_monthly: 220000,
    speed_mbps: 100,
    scheme_type: 'rent',
    fup_gb: 300,
    free_extra_quota_gb: 0,
    downgrade_speed_mbps: 10,
    device_range: '1-5',
    bandwidth_type: 'asymmetrical',
    ip_type: 'private',
    modem_rent_fee: 50000,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: null,
    promo_type: 'normal',
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-2',
    name: 'Home 1D 300Mbps',
    price_monthly: 350000,
    speed_mbps: 300,
    scheme_type: 'rent',
    fup_gb: 600,
    free_extra_quota_gb: 50,
    downgrade_speed_mbps: 25,
    device_range: '1-10',
    bandwidth_type: 'asymmetrical',
    ip_type: 'private',
    modem_rent_fee: 50000,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: null,
    promo_type: 'normal',
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-3',
    name: 'Home 2D 400Mbps',
    price_monthly: 450000,
    speed_mbps: 400,
    scheme_type: 'rent',
    fup_gb: 900,
    free_extra_quota_gb: 100,
    downgrade_speed_mbps: 50,
    device_range: '1-15',
    bandwidth_type: 'asymmetrical',
    ip_type: 'private',
    modem_rent_fee: 50000,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: null,
    promo_type: 'normal',
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-4',
    name: 'Home 3D 500Mbps',
    price_monthly: 600000,
    speed_mbps: 500,
    scheme_type: 'rent',
    fup_gb: 1200,
    free_extra_quota_gb: 200,
    downgrade_speed_mbps: 75,
    device_range: '1-20',
    bandwidth_type: 'symmetrical',
    ip_type: 'public',
    modem_rent_fee: 50000,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: 'Gamers Edition',
    promo_type: 'normal',
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-5',
    name: 'Home 0D 100Mbps',
    price_monthly: 220000,
    speed_mbps: 100,
    scheme_type: 'buy',
    fup_gb: 300,
    free_extra_quota_gb: 0,
    downgrade_speed_mbps: 10,
    device_range: '1-5',
    bandwidth_type: 'asymmetrical',
    ip_type: 'private',
    modem_rent_fee: 0,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: null,
    promo_type: 'normal',
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-6',
    name: 'Home 1D 300Mbps',
    price_monthly: 350000,
    speed_mbps: 300,
    scheme_type: 'buy',
    fup_gb: 600,
    free_extra_quota_gb: 50,
    downgrade_speed_mbps: 25,
    device_range: '1-10',
    bandwidth_type: 'asymmetrical',
    ip_type: 'private',
    modem_rent_fee: 0,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: null,
    promo_type: 'normal',
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-7',
    name: 'Home 2D 400Mbps',
    price_monthly: 450000,
    speed_mbps: 400,
    scheme_type: 'buy',
    fup_gb: 900,
    free_extra_quota_gb: 100,
    downgrade_speed_mbps: 50,
    device_range: '1-15',
    bandwidth_type: 'asymmetrical',
    ip_type: 'private',
    modem_rent_fee: 0,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: null,
    promo_type: 'normal',
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
  {
    id: 'mock-8',
    name: 'Home 3D 500Mbps',
    price_monthly: 600000,
    speed_mbps: 500,
    scheme_type: 'buy',
    fup_gb: 1200,
    free_extra_quota_gb: 200,
    downgrade_speed_mbps: 75,
    device_range: '1-20',
    bandwidth_type: 'symmetrical',
    ip_type: 'public',
    modem_rent_fee: 0,
    installation_fee: 150000,
    ppn_percent: 11,
    badge_label: 'Gamers Edition',
    promo_type: 'normal',
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    updated_by: null,
  },
]

// Admin dummy
export const MOCK_ADMIN = { id: 'mock-admin', full_name: 'Admin Dev', role: 'admin' as const, email: 'admin@dev.com' }
